-- APIC Database Schema
-- PostgreSQL 15+ Compatible
-- Auto-generated by installer

-- ============================================================================
-- Extensions
-- ============================================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- Tables
-- ============================================================================

-- Projects table - stores project metadata
CREATE TABLE IF NOT EXISTS projects (
    id VARCHAR(36) PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    client_name VARCHAR(255) NOT NULL,
    project_name VARCHAR(255) NOT NULL,
    description TEXT,
    target_departments JSONB DEFAULT '[]'::jsonb,
    status VARCHAR(50) DEFAULT 'created' CHECK (status IN (
        'created',
        'ingesting',
        'analyzing',
        'interview_ready',
        'awaiting_transcript',
        'processing_transcript',
        'solutioning',
        'reporting',
        'completed',
        'failed'
    )),
    vector_namespace VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Project states table - workflow state persistence for human breakpoint
CREATE TABLE IF NOT EXISTS project_states (
    id VARCHAR(36) PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    project_id VARCHAR(36) UNIQUE NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    thread_id VARCHAR(36) UNIQUE NOT NULL,
    state_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    current_node VARCHAR(50) DEFAULT 'start',
    is_suspended BOOLEAN DEFAULT FALSE,
    suspension_reason VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Documents table - uploaded document metadata
CREATE TABLE IF NOT EXISTS documents (
    id VARCHAR(36) PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    project_id VARCHAR(36) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL CHECK (file_type IN (
        'pdf', 'docx', 'doc', 'txt', 'pptx', 'xlsx'
    )),
    file_size VARCHAR(50) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    chunk_count VARCHAR(50) DEFAULT '0',
    processed BOOLEAN DEFAULT FALSE,
    content_summary TEXT,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Projects indexes
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_client_name ON projects(client_name);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON projects(created_at DESC);

-- Project states indexes
CREATE INDEX IF NOT EXISTS idx_project_states_project_id ON project_states(project_id);
CREATE INDEX IF NOT EXISTS idx_project_states_is_suspended ON project_states(is_suspended);
CREATE INDEX IF NOT EXISTS idx_project_states_current_node ON project_states(current_node);

-- Documents indexes
CREATE INDEX IF NOT EXISTS idx_documents_project_id ON documents(project_id);
CREATE INDEX IF NOT EXISTS idx_documents_file_type ON documents(file_type);
CREATE INDEX IF NOT EXISTS idx_documents_processed ON documents(processed);

-- ============================================================================
-- Triggers
-- ============================================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to projects table
DROP TRIGGER IF EXISTS update_projects_updated_at ON projects;
CREATE TRIGGER update_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Apply trigger to project_states table
DROP TRIGGER IF EXISTS update_project_states_updated_at ON project_states;
CREATE TRIGGER update_project_states_updated_at
    BEFORE UPDATE ON project_states
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Initial Data (Optional)
-- ============================================================================

-- Insert sample project for testing (commented out by default)
-- INSERT INTO projects (client_name, project_name, description, target_departments)
-- VALUES (
--     'Demo Company',
--     'Initial Assessment',
--     'Demonstration project for APIC system',
--     '["Finance", "Operations"]'::jsonb
-- ) ON CONFLICT DO NOTHING;

-- ============================================================================
-- Grants (adjust as needed for your setup)
-- ============================================================================

-- Grant permissions to application user (if different from owner)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO apic_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO apic_user;
